### ISSUE TITLE
Suggestion of Discussing Compositional Generalization of MCTG

### ISSUE THREAD

**Issue by Zhaoyi-Li21** [IAAR-Shanghai/CTGSurvey#3]
Hey, thanks for the great work and the comprehensive survey!

Recently our paper [Benchmarking and Improving Compositional Generalization of Multi-aspect Controllable Text Generation (ACL'24)](https://aclanthology.org/2024.acl-long.351/) discussed a challenge "compositional generalization" that frequently occurs in MCTG scenarios. (which was also discussed in the paper [DCG (ACL'23)](https://aclanthology.org/2023.acl-long.793/) in the controlled dialogue generation scenarios.) I believe discussing this issue would be a good complement to the Section 9 (CHALLENGES AND APPEALS) of the survey.

It would be so nice if you could consider adding such content to the paper in the next revised version.

Best Regards,
Zhaoyi

**Comment by MarrytheToilet** [comment]
Thank you, Dr. Zhao, for your attention to our work! In fact, we had already noticed your work on X and have included it in our next update plan. Additionally, we sent you a message on X to inform you about this, but it might have been blocked.

Here is the content of the message we sent you: "Hello, Dr. Li, Today, we came across your work on 'Benchmarking and Improving Compositional Generalization of Multi-aspect Controllable Text Generation.' This is a very meaningful benchmark contribution! We just released 'Controllable Text Generation for Large Language Models: A Survey' today, and we plan to include your paper in the benchmarks section in our next update."

Once again, thank you for your attention to our work, and we hope to have more opportunities for collaboration and communication in the future!

**Comment by Zhaoyi-Li21** [comment]
Hi Haoyu,

That would be very lovely. The twitter message was indeed blocked (sorry!). Thanks again for the very informative survey on CTG. I am looking forward to more works (on controlling LLMs' output) from you (and the group).

Best Regards,
Zhaoyi
